### ISSUE TITLE
Tour autostart

### ISSUE THREAD

**Issue by claymcleod** [stjude/sjcloud-data-transfer-app#1]
Autostarting the tour on first login seems to mess up the loading of projects sometimes. Let's just have something pop-up to show the user the _they_ can start the tour rather than doing it automatically.

**Comment by siosonel** [comment]
@claymcleod I decided the best approach is wait for the tools download before triggering the tour auto-start, with a maximum number of tries before canceling the auto-start.

I also take back my suggestion earlier to use a fake tools list in the tour, when the user has no projects. Preventing the auto-start when there are no tools should cover most the cases, and we could revisit if the edge cases happens often enough.

**Comment by claymcleod** [comment]
Okay, sounds good. Thanks, Edgar.
