### ISSUE TITLE
Code climate score to C

### ISSUE THREAD

**Issue by claymcleod** [stjude/sjcloud-data-transfer-app#12]
Use the badge in the README.md to find the Code Climate page. We need to get this score to a 'C'.

**Comment by siosonel** [comment]
@claymcleod With regards to improving the code in store.js, I'm thinking of drastically simplifying the getters and mutations by replacing a bunch of those functions with a generic getters.byKey("key1") and commit("byKey",{key1:val1,...}). This would affect a lot of other code, so before I start it I'd like to see what you think.

**Comment by claymcleod** [comment]
How easy do you think it would be to set up some basic unit tests on this before making changes? Is it feasible to make headway do in a relatively short amount of time? Since this issue is not pressing, I'd like to build in the tests as we make improvements to the code, but I'm not sure about how building tests for this piece of it goes.

**Comment by siosonel** [comment]
The existing karma tests should work for the most part. It'll be a lot of find and replace, across many vue files, so it'll be good to not have anyone else working on vue templates at the same time or else it might be confusing to rebase/merge.

**Comment by claymcleod** [comment]
Agreed. Just let me know when you start working on that piece and I'll stop.

@a-frantz FYI.

**Comment by claymcleod** [comment]
In our meeting today, @siosonel described that he would improve parts of the Vue store for release 1.0.3, hopefully getting the code climate score up to C.
