### ISSUE TITLE
Missing OpenSSL causes login window to hang

### ISSUE THREAD

**Issue by claymcleod** [stjude/sjcloud-data-transfer-app#14]
Let's solve in three steps:

1. Check when the install screen shows up if SSL is installed and reachable. If not, show an alert saying that they need to download the binary (with link to the appropriate OpenSSL docs) and change the state of the install to show an error.
2. After completion on #15, we can just show the alert and change the state on the install screen to show an error.
3. Estimate the complexity of configuring and installing OpenSSL automatically.

**Comment by claymcleod** [comment]
@a-frantz Also, please update the README.md to include that `openssl` is a requirement.

**Comment by siosonel** [comment]
To open the alert pop-up, call `window.VueApp.$store.commit('byKey', {alertType: "info | success | warning | danger", alertMessage: "text"})`

To close, call `window.VueApp.$store.commit('byKey', {alertType: ""}) // empty alertType`
