### ISSUE TITLE
Expose dismissable alerts in UI

### ISSUE THREAD

**Issue by claymcleod** [stjude/sjcloud-data-transfer-app#15]
This issue is concerned with creating the infrastructure to easily create a red alert box that is dismissable at the top of the screen. See: https://v4-alpha.getbootstrap.com/components/alerts/

**Comment by siosonel** [comment]
To open the alert pop-up, call `window.VueApp.$store.commit('byKey', {alertType: "info | success | warning | danger", alertMessage: "text"})`

To close, call `window.VueApp.$store.commit('byKey', {alertType: ""}) // empty alertType`
