### ISSUE TITLE
Error reporting functionality

### ISSUE THREAD

**Issue by claymcleod** [stjude/sjcloud-data-transfer-app#32]
- [x] Expose an alert feature with the ability to report an issue. (After reading up on Quasar, I really liked it, so I think that with the material design theme would be good).
- [x] We need to formulate a strategy for communicating the error to our team. I'm not sure what the best strategy is, so I'll email Nedra to see if we can't figure that out. Whenever we do decide, we'll edit this point.

**Comment by siosonel** [comment]
@claymcleod There is an Alert component from Quasar that was committed in 77e2ba0009683b658c43362cfc26a04e2fbb8eeb, with a link to "https://stjude.cloud/contact" which today redirected me to "https://hospital.stjude.org/apps/forms/fb/st-jude-cloud-contact/". 

Let me know what else needs to be done for this issue. Other components could use that alert by `import { Alert } from "quasar"` then as needed `Alert.create({html: "...", actions: []})`.

**Comment by claymcleod** [comment]
@jsunny23 @siosonel Can we utilize this alert to report a failure in the general case?

**Comment by siosonel** [comment]
I'm okay with receiving alerts.
