### ISSUE TITLE
Fixes to styling

### ISSUE THREAD

**Issue by claymcleod** [stjude/sjcloud-data-transfer-app#34]
## Tasks

- [x] Left-align "Size" label to the "B" in "767 GB".
- [x] Center align "CLICK OR DROP FILES HERE".

## Pictures 

<img width="298" alt="screen shot 2017-12-10 at 7 52 13 am" src="https://user-images.githubusercontent.com/3411613/33805473-2ac009e8-dd7f-11e7-8592-4d6fb1ed7a82.png">

<img width="568" alt="screen shot 2017-12-10 at 7 58 39 am" src="https://user-images.githubusercontent.com/3411613/33805535-1c195bfa-dd80-11e7-8e0b-acb1bf533726.png">

**Comment by siosonel** [comment]
Fixed in commit 6c7b352
